services:
- docker
before_install:
- docker pull vartanovs/sv-homepage
- docker pull vartanovs/sv-homepage-dev
script:
- docker-compose -f docker/docker-compose-test.yml up --abort-on-container-exit
before_deploy:
- pip install --user awscli
- pip install --user awsebcli
- export PATH=$PATH:$HOME/.local/bin
deploy:
- provider: script
  script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh
  on:
    branch: master
  skip_cleanup: true