# set the base image to Ubuntu
# https://hub.docker.com/_/ubuntu/
FROM ubuntu:18.04

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# install depencencies
RUN apt-get update \
    && apt-get install -y curl \
    && apt-get -y autoclean

# create nvm directory
RUN mkdir -p /usr/local/nvm

# node version manager nvm environment variables
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 10.14.1

# install node version manager
# https://github.com/creationix/nvm#install-script
RUN curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

# install node and npm
RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# add node and nvm to path so the commands are available
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# confirm installation
RUN node -v
RUN npm -v