# This will start a sv-homepage-dev container named sv-homepage-test and run 'npm run test:coverage'
# Command to run: docker-compose -f docker/docker-compose-test.yml up --abort-on-container-exit
# NPM Script: npm run docker-test

version: "3"

services:
  test:
    image: vartanovs/sv-homepage-dev
    container_name: "sv-homepage-test"
    ports:
      - "3000:3000"
    volumes:
      - coverage:/usr/src/app/coverage
    command: ["npm", "run", "test:coverage"]

volumes:
  coverage:
